source_service:
  is_use_source: true # grounded or not grounded. If not grounded, meaning just Q&A via LLM
  is_enable_bing_search: true
  is_enable_doc_search: false
  doc_search_path:
  bing_search:
    end_point: https://api.bing.microsoft.com
    subscription_key:
    result_count: 3
    text_extract: trafilatura # beautifulsoup / trafilatura
llm_service:
  provider: openai # openai/goose_ai
  openai_api:
    api_key:
    # model: gpt-3.5-turbo is the best one. Details: https://platform.openai.com/docs/models/gpt-3-5.
  #  model: text-babbage-001
  #  model: text-curie-001
  #  model: text-davinci-003
    model: gpt-3.5-turbo # default
    max_tokens: 300
    temperature: 1
    top_p: 1
    prompt:
      prompt_length_limit: 3000
    stream: true
  goose_ai_api:
    api_key:
    api_base: https://api.goose.ai/v1
    # https://goose.ai/docs/models
    model: gpt-neo-20b
    max_tokens: 100
cache:  # .cache result for efficiency and consistency
  is_enable:
    web: false
    bing_search_website: false
    bing_search_website_content: false
    openai: false
    gooseai: false
  path: .cache
  max_number_of_cache: 50
